### ISSUE TITLE
NullPointerException: Player Synchronization

### ISSUE THREAD

**Issue by IanWONeill** [IanWONeill/VirtueOS#2]
`java.lang.NullPointerException
	at com.oldscape.shared.model.Position.getLocalX(Position.java:73)
	at com.oldscape.server.game.model.WalkingQueue.needsRegionUpdate(WalkingQueue.java:273)
	at com.oldscape.server.game.model.WalkingQueue.handleRegionChange(WalkingQueue.java:253)
	at com.oldscape.server.game.model.WalkingQueue.pulse(WalkingQueue.java:243)
	at com.oldscape.server.game.model.sync.task.PrePlayerSynchronizationTask.run(PrePlayerSynchronizationTask.java:30)
	at com.oldscape.server.game.model.sync.task.PhasedSynchronizationTask.run(PhasedSynchronizationTask.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by IanWONeill** [comment]
Can be tied in with https://github.com/IanWONeill/VirtueOS/issues/4
