### ISSUE TITLE
RuntimeException:  Re-Login

### ISSUE THREAD

**Issue by IanWONeill** [IanWONeill/VirtueOS#3]
`Error: ai.hu() | com.oldscape.ai.hu com.oldscape.client.gx com.oldscape.client.ft com.oldscape.client.at com.oldscape.br.g com.oldscape.br.run Thread:748 | java.lang.RuntimeException: 679,23 | 33,40,82,23,3222,3222,0,0,3,8,6,40,32,0,80,-128,98,-126,-1,-2,2,25,45,25,-83,25,45,25,-83,`

**Comment by IanWONeill** [comment]
This is only an issue with the Transformed.jar Client, doing a Re-Login with the RuneLite reference Client will work fine?

**Comment by IanWONeill** [comment]
`java.lang.RuntimeException: 679,23
	at com.oldscape.client.reference.WorldMapRegion.updateNpcs(WorldMapRegion.java:233)
	at com.oldscape.client.reference.Client.method1265(Client.java:4578)
	at com.oldscape.client.reference.Client.method1261(Client.java:2905)
	at com.oldscape.client.reference.Client.packetHandler(Client.java:2116)
	at com.oldscape.client.reference.GameEngine.method1015(GameEngine.java:619)
	at com.oldscape.client.reference.GameEngine.run(GameEngine.java:872)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by IanWONeill** [comment]
Yes, So if a player logs in (the Npc is spawned +1 X/Y offset the players position) and moves position then Logs out - upon Login there will be no issue and a new Npc will be spawned. BUT if the player doesn't move and the player logs in where by the Npc will spawn in the Same location as previously, the error will be thrown in `updateNpcs`.
