### ISSUE TITLE
OutOfMemoryError: Loading Region

### ISSUE THREAD

**Issue by IanWONeill** [IanWONeill/VirtueOS#5]
`Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
	at com.oldscape.client.reference.WorldMapType3.decodeContainer(WorldMapType3.java:69)
	at com.oldscape.client.reference.IndexDataBase.buildRecords(IndexDataBase.java:373)
	at com.oldscape.client.reference.IndexDataBase.getConfigDataKeys(IndexDataBase.java:197)
	at com.oldscape.client.reference.Client.packetHandler(Client.java:1158)
	at com.oldscape.client.reference.GameEngine.method1015(GameEngine.java:619)
	at com.oldscape.client.reference.GameEngine.run(GameEngine.java:872)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by IanWONeill** [comment]
var51 0
field1139[var51] [B@152526f2
xteaKeys[var51][I@3603dc47
var51 1
field1139[var51] [B@3a51a16c
xteaKeys[var51][I@57cf9987
var51 2
field1139[var51] [B@6be1273a
xteaKeys[var51][I@43283fe5
var51 3
field1139[var51] [B@74c5bc2d
xteaKeys[var51][I@5f6d1093
Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
	at com.oldscape.client.reference.WorldMapType3.decodeContainer(WorldMapType3.java:69)
	at com.oldscape.client.reference.IndexDataBase.buildRecords(IndexDataBase.java:373)
	at com.oldscape.client.reference.IndexDataBase.getConfigDataKeys(IndexDataBase.java:197)
	at com.oldscape.client.reference.Client.packetHandler(Client.java:1158)
	at com.oldscape.client.reference.GameEngine.method1015(GameEngine.java:619)
	at com.oldscape.client.reference.GameEngine.run(GameEngine.java:872)
	at java.lang.Thread.run(Thread.java:748)

**Comment by IanWONeill** [comment]
Can be tied in with https://github.com/IanWONeill/VirtueOS/issues/4
